# Generated by Django 4.0.6 on 2022-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(default='None', max_length=20)),
                ('time', models.PositiveIntegerField()),
                ('type', models.CharField(default='None', max_length=20)),
                ('price', models.CharField(default='None', max_length=20)),
                ('difficulty', models.CharField(default='None', max_length=20)),
                ('companions', models.CharField(default='None', max_length=20)),
                ('transport', models.CharField(default='None', max_length=20)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
