# Generated by Django 4.0.6 on 2022-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='time_stamp',
            field=models.DateTimeField(max_length=200),
        ),
    ]
