# Generated by Django 4.0.6 on 2022-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_users_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='time_stamp',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
